name: Build Windows (Electron)

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - "electron/**"
      - "src/**"
      - "package.json"
      - "vite.config.ts"
      - "tsconfig*.json"
      - "supabase/**"

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Build renderer (Vite)
        run: npm run build

      - name: Build Electron app (Windows)
        run: |
          npm run build
          npx electron-builder --win --publish never

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: branch-gear-pro-windows
          path: |
            release/**
          if-no-files-found: error
